lsi: false
safe: true
url: "https://codeabilitypodcast.github.io"
baseurl: ""

title: CodeAbility Podcast
description: ğŸ™ï¸ Amplifying the voices of people with disabilities in tech
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 

incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
